name: reg-prix-football
channels:
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - pip:
      - tensorflow
      - Scikit-learn 
      - Matplotlib 
      - plotly 
      - seaborn 
      - Pandas 
      - requests
      - bs4
      - Jupyterlab
 

